package com.example.practicekotlin.user.repository

import com.example.practicekotlin.user.entity.UserEntity
import com.example.practicekotlin.user.service.UserRepository
import java.util.concurrent.atomic.AtomicLong

class FakeUserRepository : UserRepository {

    private val autoGeneratedId: AtomicLong = AtomicLong(0)
    private val users: ArrayList<UserEntity> = ArrayList()

    override fun create(user: UserEntity) {
        if (user.id == null) {
            UserEntity(
                id = autoGeneratedId.incrementAndGet(),
                loginId = user.loginId,
                password = user.password
            )
            users.add(user)
            return
        }

        users.removeIf { u -> u.id == user.id }
        users.add(user)
    }

}